[project]
name = "data-agent-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncmy>=0.2.14",
    "cryptography>=50.0.1",
    "elasticsearch[async]>=8,<9",
    "jieba>=0.42.1",
    "langchain>=1.4.0",
    "langchain-deepseek>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "loguru>=0.7.3",
    "omegaconf>=2.3.1",
    "qdrant-client>=1.19.0",
    "sqlalchemy>=2.0.52",
]
